error logs wasnt sent to stderr

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -60,8 +60,8 @@ if [[ ${http_code} -eq '200' ]]; then
   fi
   exit 0
 else
-  echo "Unable to retreive versions in artifactory"
-  echo "Request: curl -k -X POST -H "X-JFrog-Art-Api:${api_key}" -H "Content-Type:text/plain" -d "${aql}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql"
-  echo "Error:${req_output}"
+  echo "Unable to retreive versions in artifactory" >&2
+  echo "Request: curl -k -X POST -H "X-JFrog-Art-Api:${api_key}" -H "Content-Type:text/plain" -d "${aql}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql" >&2
+  echo "Error:${req_output}" >&2
   exit 1
 fi
diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -88,8 +88,8 @@ if [[ ${http_code} -eq '200' ]]; then
   echo $(echo "\"${version}\"" | jq "{version: {ref: .}, metadata: $(echo ${metadata_folder} | jq ". + ${metadata_files}")}") >&3
   exit 0
 else
-  echo "Unable to retreive files in artifactory"
-  echo "Request: curl -k -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d "${aql_files}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql"
-  echo "Error:${req_files}"
+  echo "Unable to retreive files in artifactory" >&2
+  echo "Request: curl -k -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d "${aql_files}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql" >&2
+  echo "Error:${req_files}" >&2
   exit 1
 fi
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -41,7 +41,7 @@ folder_exists "${destination}/${path_param}"
 
 version=$(get_version "${payload}" "${destination}")
 if [[ "${?}" -ne '0' ]]; then
-  echo "${version}"
+  echo "${version}" >&2
   exit 1
 fi
 group_id_path=$(echo "${group_id}" | sed 's/\./\//g')
@@ -78,9 +78,9 @@ for abs_file in $files; do
       --silent \
       ${host}/${repository_id}/${group_id_path}/${artifact_id}/${version}/${file})
   elif [[ ${http_code} -ne '201' ]]; then
-    echo "An error occured while trynig to create artifact ${file} by checksum"
-    echo "Request: curl -k -H 'X-JFrog-Art-Api:*****' -H "X-Checksum-Sha1:${sha1}" -H "X-Checksum-Sha256: ${sha256}" -T "${abs_file}" --silent ${host}/${repository_id}/${group_id_path}/${artifact_id}/${version}/${file}"
-    echo "Error:${req_output}"
+    echo "An error occured while trynig to create artifact ${file} by checksum" >&2
+    echo "Request: curl -k -H 'X-JFrog-Art-Api:*****' -H "X-Checksum-Sha1:${sha1}" -H "X-Checksum-Sha256: ${sha256}" -T "${abs_file}" --silent ${host}/${repository_id}/${group_id_path}/${artifact_id}/${version}/${file}" >&2
+    echo "Error:${req_output}" >&2
     exit 1
   fi
 
