Don't fetch artifacts anynomously. Improve error handling when no artifacts are found

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -69,26 +69,34 @@ result_files=$(curl \
 http_code="${result_files##*$'\n'}"
 req_files=$(echo "${result_files}" | sed '$d')
 
-echo "${version}" > $destination/version
-
 if [[ ${http_code} -eq '200' ]]; then
   length=$(echo ${req_files} | jq '.results|length')
-  for (( i=0; i<$((length)); i++)); do
-    file_name=$(echo ${req_files} | jq -r ".results[${i}].name")
-    echo "Downloading ${file_name}"
-    curl \
-      -k \
-      -o "${1}/${file_name}" \
-      --silent \
-      "${host}/${repository_id}/$(echo ${req_files} | jq -r ".results[${i}]|\"\(.path)/\(.name)\"")"
-  done
+  if (( ${length} > 0 )); then
+    echo "${version}" > $destination/version
+    for (( i=0; i<$((length)); i++)); do
+      file_name=$(echo ${req_files} | jq -r ".results[${i}].name")
+      echo "Downloading ${file_name}"
+      curl \
+        -k \
+        -H "X-JFrog-Art-Api:${api_key}" \
+        -o "${1}/${file_name}" \
+        --silent \
+        "${host}/${repository_id}/$(echo ${req_files} | jq -r ".results[${i}]|\"\(.path)/\(.name)\"")"
+    done
 
-  metadata_folder=$(folder_metadata "${payload}" "${destination}" "${version}")
-  metadata_files=$(echo ${req_files} | jq '[[.results[].name]|to_entries[]|{name: "file_\(.key)", value}]')
-  echo $(echo "\"${version}\"" | jq "{version: {ref: .}, metadata: $(echo ${metadata_folder} | jq ". + ${metadata_files}")}") >&3
-  exit 0
+    metadata_folder=$(folder_metadata "${payload}" "${destination}" "${version}")
+    metadata_files=$(echo ${req_files} | jq '[[.results[].name]|to_entries[]|{name: "file_\(.key)", value}]')
+    echo $(echo "\"${version}\"" | jq "{version: {ref: .}, metadata: $(echo ${metadata_folder} | jq ". + ${metadata_files}")}") >&3
+    exit 0
+  else
+    echo 'Unable to retreive files in artifactory.' >&2
+    echo 'Make sure to use the correct values ​​in the source:' >&2
+    echo "artifact_id: '${artifact_id}'" >&2
+    echo "group_id: '${group_id}'" >&2
+    echo "repository_id: '${repository_id}'" >&2
+  fi
 else
-  echo "Unable to retreive files in artifactory" >&2
+  echo "Unable to retreive files in artifactory." >&2
   echo "Request: curl -k -X POST -H 'X-JFrog-Art-Api:*****' -H 'Content-Type:text/plain' -d "${aql_files}" --write-out "\n%{http_code}" --silent ${host}/api/search/aql" >&2
   echo "Error:${req_files}" >&2
   exit 1
